version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  deploy-on-heroku:
    steps:
      - checkout
      - run:
          name: Deploy on Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STG.git master

workflows:
    deploy:
      jobs:
        - build-and-test   
        - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master   