version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor: 
      name: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  build-test-deploy:
    jobs:
      - build-and-test   
      - deploy: 
          requires:
            - build-and-test
          filters:
            branches:
              only: master   